# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 352c87cfb271b98d60fcb90c3c6e48a2b371472e8793f236f33665112f6b0c4aadce62d08826cff872038815012973ff49c790962656f457792988f2bfbd326d

test:
  secret_key_base: 0dae4cfc3f84e3c046c740e1de58f0e1482a444a79409fd050b666cb14ffaffe7fb924bbda8489ad7c7e3065d8ce143d8e1dfb0073c9577d7480e3486c6d349d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
